#!/usr/bin/env python3
"""Replace bare URL docs with structured {title, url, summary} entries in lessons.json."""

import json
import sys

def main():
    with open("src/lessons.json") as f:
        data = json.load(f)

    # Map URL → (title, summary) for every doc reference
    DOCS = "https://nim-lang.org/docs"
    MANUAL = f"{DOCS}/manual.html"
    TUT1 = f"{DOCS}/tut1.html"
    TUT2 = f"{DOCS}/tut2.html"

    def doc(title, url, summary=""):
        return {"title": title, "url": url, "summary": summary}

    # Build the mapping
    m = {
        # Tutorial 1 anchors
        f"{TUT1}#hello-world": doc("Tutorial - Hello World",
            f"{TUT1}#hello-world",
            "Nim's official introduction: hello world, basic syntax, and your first program."),
        f"{TUT1}#compiling-and-running": doc("Tutorial - Compiling",
            f"{TUT1}#compiling-and-running",
            "How to compile and run Nim programs with `nim c -r`."),
        f"{TUT1}#io": doc("Tutorial - Input/Output",
            f"{TUT1}#io",
            "Reading from stdin and writing to stdout with echo, readLine, writeFile, readFile."),
        f"{TUT1}#variables": doc("Tutorial - Variables",
            f"{TUT1}#variables",
            "Declaring variables with let and var, type inference, and basic types."),
        f"{TUT1}#basic-types": doc("Tutorial - Basic Types",
            f"{TUT1}#basic-types",
            "Nim's built-in types: int, float, string, bool, char, and their usage."),
        f"{TUT1}#strings": doc("Tutorial - Strings",
            f"{TUT1}#strings",
            "String literals, escaping, concatenation, and basic string operations."),
        f"{TUT1}#procedures": doc("Tutorial - Procedures",
            f"{TUT1}#procedures",
            "Defining and calling procedures, parameters, return types, and recursion."),
        f"{TUT1}#if-expression": doc("Tutorial - If Expressions",
            f"{TUT1}#if-expression",
            "Conditional branching with if, elif, and else."),
        f"{TUT1}#case-statement": doc("Tutorial - Case Statement",
            f"{TUT1}#case-statement",
            "Pattern matching with case/switch statements."),
        f"{TUT1}#for-loops": doc("Tutorial - For Loops",
            f"{TUT1}#for-loops",
            "Iteration with for loops over ranges, sequences, and strings."),
        f"{TUT1}#while-loops": doc("Tutorial - While Loops",
            f"{TUT1}#while-loops",
            "Conditional looping with while and related control flow."),
        f"{TUT1}#sequences": doc("Tutorial - Sequences",
            f"{TUT1}#sequences",
            "Dynamic arrays (seq), creation, iteration, and common operations."),
        f"{TUT1}#tuples": doc("Tutorial - Tuples",
            f"{TUT1}#tuples",
            "Fixed-size collections of mixed types, field access, and unpacking."),
        f"{TUT1}#enums": doc("Tutorial - Enums",
            f"{TUT1}#enums",
            "Enumeration types, ordinal values, and their usage in Nim."),
        f"{TUT1}#exception-handling": doc("Tutorial - Exception Handling",
            f"{TUT1}#exception-handling",
            "Raising and catching exceptions with try/except/finally."),
        f"{TUT1}#file-operations": doc("Tutorial - File Operations",
            f"{TUT1}#file-operations",
            "Reading and writing files with the standard library."),
        TUT1: doc("Tutorial (Part 1)",
            TUT1,
            "Nim's official beginner tutorial covering syntax, types, control flow, and I/O."),
        f"{TUT1}#type-aliases": doc("Tutorial - Type Aliases",
            f"{TUT1}#type-aliases",
            "Creating aliases for existing types to improve readability."),

        # Tutorial 2 anchors
        f"{TUT2}#objects": doc("Tutorial Part 2 - Objects",
            f"{TUT2}#objects",
            "Object-oriented programming in Nim: defining objects, fields, and methods."),
        f"{TUT2}#generics": doc("Tutorial Part 2 - Generics",
            f"{TUT2}#generics",
            "Generic procedures and types for reusable, type-safe code."),
        f"{TUT2}#modules": doc("Tutorial Part 2 - Modules",
            f"{TUT2}#modules",
            "Organizing code into modules, import/export rules, and project structure."),
        f"{TUT2}#references-and-pointers": doc("Tutorial - References & Pointers",
            f"{TUT2}#references-and-pointers",
            "Ref types, pointers, memory management, and when to use each."),
        f"{TUT2}#templates": doc("Tutorial Part 2 - Templates",
            f"{TUT2}#templates",
            "Compile-time code generation with template metaprogramming."),
        f"{TUT2}#c-interfacing": doc("Tutorial Part 2 - C Interfacing",
            f"{TUT2}#c-interfacing",
            "Calling C libraries from Nim and exporting Nim code to C."),
        f"{TUT2}#macros": doc("Tutorial Part 2 - Macros",
            f"{TUT2}#macros",
            "Compile-time code transformation using Nim's macro system."),
        f"{TUT2}#concepts": doc("Tutorial Part 2 - Concepts",
            f"{TUT2}#concepts",
            "Type classes and concepts for constraining generic parameters."),
        TUT2: doc("Tutorial (Part 2)",
            TUT2,
            "Nim's intermediate tutorial covering generics, objects, templates, macros, and FFI."),

        # Manual anchors
        f"{MANUAL}#lexical-analysis-comments": doc("Manual - Comments",
            f"{MANUAL}#lexical-analysis-comments",
            "Single-line (#) and multi-line (#[...]#) comment syntax."),
        f"{MANUAL}#lexical-analysis-string-literals": doc("Manual - String Literals",
            f"{MANUAL}#lexical-analysis-string-literals",
            "String syntax: escape sequences, raw strings, triple-quoted multiline strings."),
        f"{MANUAL}#types": doc("Manual - Types",
            f"{MANUAL}#types",
            "Complete reference for Nim's type system."),
        f"{MANUAL}#type-inference": doc("Manual - Type Inference",
            f"{MANUAL}#type-inference",
            "How the Nim compiler infers types from context."),
        f"{MANUAL}#var-statement": doc("Manual - Var Statement",
            f"{MANUAL}#var-statement",
            "Declaration and initialization of variables with let and var."),
        f"{MANUAL}#constant-expressions-and-const-binding": doc("Manual - Const",
            f"{MANUAL}#constant-expressions-and-const-binding",
            "Compile-time constant evaluation with the const keyword."),
        f"{MANUAL}#type-conversions": doc("Manual - Type Conversions",
            f"{MANUAL}#type-conversions",
            "Explicit type conversion using int(), float(), $, and other converters."),
        f"{MANUAL}#distinct-type": doc("Manual - Distinct Types",
            f"{MANUAL}#distinct-type",
            "Creating type-safe wrappers around existing types with distinct."),
        f"{MANUAL}#subrange-types": doc("Manual - Subrange Types",
            f"{MANUAL}#subrange-types",
            "Restricting values to a specific range using range types."),
        f"{MANUAL}#type-aliases": doc("Manual - Type Aliases",
            f"{MANUAL}#type-aliases",
            "Creating alternative names for existing types."),
        f"{MANUAL}#procedures": doc("Manual - Procedures",
            f"{MANUAL}#procedures",
            "Full reference for proc declarations, parameters, return types, and calling conventions."),
        f"{MANUAL}#if-statement": doc("Manual - If Statement",
            f"{MANUAL}#if-statement",
            "Conditional execution with if, elif, and else branches."),
        f"{MANUAL}#for-statement": doc("Manual - For Statement",
            f"{MANUAL}#for-statement",
            "Iteration over ranges, collections, and custom iterators."),
        f"{MANUAL}#while-statement": doc("Manual - While Statement",
            f"{MANUAL}#while-statement",
            "Looping while a condition holds true."),
        f"{MANUAL}#case-statement": doc("Manual - Case Statement",
            f"{MANUAL}#case-statement",
            "Pattern matching with case and when statements."),
        f"{MANUAL}#break-statement": doc("Manual - Break Statement",
            f"{MANUAL}#break-statement",
            "Early exit from loops using break and named blocks."),
        f"{MANUAL}#continue-statement": doc("Manual - Continue Statement",
            f"{MANUAL}#continue-statement",
            "Skipping to the next loop iteration with continue."),
        f"{MANUAL}#tuple-types": doc("Manual - Tuple Types",
            f"{MANUAL}#tuple-types",
            "Fixed-size heterogeneous collections with named or positional fields."),
        f"{MANUAL}#object-types": doc("Manual - Object Types",
            f"{MANUAL}#object-types",
            "Defining structured data types with fields and inheritance."),
        f"{MANUAL}#seq-type": doc("Manual - Seq Type",
            f"{MANUAL}#seq-type",
            "Dynamic arrays in Nim: creation, indexing, and operations."),
        f"{MANUAL}#enum-types": doc("Manual - Enum Types",
            f"{MANUAL}#enum-types",
            "Enumeration types with ordinal values, custom values, and string conversion."),
        f"{MANUAL}#method-call-syntax": doc("Manual - Method Call Syntax",
            f"{MANUAL}#method-call-syntax",
            "Calling procs with obj.method() syntax for cleaner code."),
        f"{MANUAL}#set-type": doc("Manual - Set Type",
            f"{MANUAL}#set-type",
            "Bit-set collections for efficient membership testing."),
        f"{MANUAL}#ref-types": doc("Manual - Ref Types",
            f"{MANUAL}#ref-types",
            "Reference types for shared mutable state and garbage collection."),
        f"{MANUAL}#ptr-type": doc("Manual - Ptr Type",
            f"{MANUAL}#ptr-type",
            "Raw pointers for low-level memory access and FFI."),
        f"{MANUAL}#move-semantics": doc("Manual - Move Semantics",
            f"{MANUAL}#move-semantics",
            "Ownership transfer with move for ARC/ORC memory management."),
        f"{MANUAL}#destructors": doc("Manual - Destructors",
            f"{MANUAL}#destructors",
            "Custom cleanup logic with =destroy hooks."),
        f"{MANUAL}#copy-constructors": doc("Manual - Copy Constructors",
            f"{MANUAL}#copy-constructors",
            "Custom copy behavior with =copy hooks for resource management."),
        f"{MANUAL}#sink-parameters": doc("Manual - Sink Parameters",
            f"{MANUAL}#sink-parameters",
            "Optimization parameters that move rather than copy data."),
        f"{MANUAL}#defer-statement": doc("Manual - Defer",
            f"{MANUAL}#defer-statement",
            "Scheduling cleanup code to run when scope exits, even on exceptions."),
        f"{MANUAL}#import-statement": doc("Manual - Import Statement",
            f"{MANUAL}#import-statement",
            "Bringing external module symbols into scope."),
        f"{MANUAL}#from-import-statement": doc("Manual - From/Import",
            f"{MANUAL}#from-import-statement",
            "Selectively importing specific symbols from a module."),
        f"{MANUAL}#include-statement": doc("Manual - Include",
            f"{MANUAL}#include-statement",
            "Textually inserting one file's contents into another."),
        f"{MANUAL}#export-statement": doc("Manual - Export",
            f"{MANUAL}#export-statement",
            "Re-exporting symbols from imported modules."),
        f"{MANUAL}#generics": doc("Manual - Generics",
            f"{MANUAL}#generics",
            "Generic procedures, types, and constraints."),
        f"{MANUAL}#generics-type-classes": doc("Manual - Type Classes",
            f"{MANUAL}#generics-type-classes",
            "Constraining generic parameters with type classes like SomeInteger."),
        f"{MANUAL}#generic-objects": doc("Manual - Generic Objects",
            f"{MANUAL}#generic-objects",
            "Objects with generic type parameters for reusable data structures."),
        f"{MANUAL}#iterators-and-the-for-statement": doc("Manual - Iterators",
            f"{MANUAL}#iterators-and-the-for-statement",
            "Defining custom iterators with yield for lazy sequences."),
        f"{MANUAL}#templates": doc("Manual - Templates",
            f"{MANUAL}#templates",
            "Compile-time code substitution with templates."),
        f"{MANUAL}#static-params": doc("Manual - Static Params",
            f"{MANUAL}#static-params",
            "Compile-time parameters for generic code specialization."),
        f"{MANUAL}#when-statement": doc("Manual - When Statement",
            f"{MANUAL}#when-statement",
            "Compile-time conditional compilation with when."),
        f"{MANUAL}#operators": doc("Manual - Operators",
            f"{MANUAL}#operators",
            "Custom operator definitions and precedence rules."),
        f"{MANUAL}#pragma-operators": doc("Manual - Pragma Operators",
            f"{MANUAL}#pragma-operators",
            "Controlling operator precedence and associativity with pragmas."),
        f"{MANUAL}#assignment-operators": doc("Manual - Assignment Operators",
            f"{MANUAL}#assignment-operators",
            "Custom copy and move assignment semantics."),
        f"{MANUAL}#object-variants": doc("Manual - Object Variants",
            f"{MANUAL}#object-variants",
            "Discriminated unions with type-safe variant fields."),
        f"{MANUAL}#multi-methods": doc("Manual - Multi-Methods",
            f"{MANUAL}#multi-methods",
            "Dynamic dispatch based on runtime types of multiple arguments."),
        f"{MANUAL}#concepts": doc("Manual - Concepts",
            f"{MANUAL}#concepts",
            "Defining type requirements with concept syntax."),
        f"{MANUAL}#auto-type": doc("Manual - Auto Type",
            f"{MANUAL}#auto-type",
            "Letting the compiler infer a proc's return type."),
        f"{MANUAL}#void-type": doc("Manual - Void Type",
            f"{MANUAL}#void-type",
            "The void return type for procedures that don't return a value."),
        f"{MANUAL}#exception-handling": doc("Manual - Exception Handling",
            f"{MANUAL}#exception-handling",
            "Full reference for raising, catching, and defining exceptions."),
        f"{MANUAL}#exception-hierarchy": doc("Manual - Exception Hierarchy",
            f"{MANUAL}#exception-hierarchy",
            "Nim's exception class hierarchy: CatchableError, Defect, and custom types."),
        f"{MANUAL}#effect-system": doc("Manual - Effect System",
            f"{MANUAL}#effect-system",
            "Tracking exceptions, side effects, and IO operations at the type level."),
        f"{MANUAL}#func-type": doc("Manual - Func Type",
            f"{MANUAL}#func-type",
            "Pure procedures with no side effects using the func keyword."),
        f"{MANUAL}#garbage-collector": doc("Manual - GC",
            f"{MANUAL}#garbage-collector",
            "Nim's garbage collection models and tuning options."),
        f"{MANUAL}#arc-orc-memory-management": doc("Manual - ARC/ORC",
            f"{MANUAL}#arc-orc-memory-management",
            "Modern deterministic memory management with ARC and ORC."),
        f"{MANUAL}#foreign-function-interface": doc("Manual - FFI",
            f"{MANUAL}#foreign-function-interface",
            "Calling C, C++, and Objective-C code from Nim."),
        f"{MANUAL}#calling-convention": doc("Manual - Calling Conventions",
            f"{MANUAL}#calling-convention",
            "Controlling how Nim functions are called at the ABI level."),
        f"{MANUAL}#c-interfacing-for-cpp": doc("Manual - C++ Interfacing",
            f"{MANUAL}#c-interfacing-for-cpp",
            "Wrapping C++ classes and methods from Nim code."),
        f"{MANUAL}#c-interfacing": doc("Manual - C Interfacing",
            f"{MANUAL}#c-interfacing",
            "Practical guide to binding C libraries, structs, and callbacks."),
        f"{MANUAL}#dynamic-linking": doc("Manual - Dynamic Linking",
            f"{MANUAL}#dynamic-linking",
            "Loading shared libraries at runtime with dlopen/LoadLibrary."),
        f"{MANUAL}#module-system": doc("Manual - Module System",
            f"{MANUAL}#module-system",
            "Module resolution, import rules, and cross-module visibility."),
        f"{MANUAL}#emit-pragma": doc("Manual - Emit Pragma",
            f"{MANUAL}#emit-pragma",
            "Embedding raw C code directly in Nim source files."),
        f"{MANUAL}#inline-pragma": doc("Manual - Inline Pragma",
            f"{MANUAL}#inline-pragma",
            "Hinting the compiler to inline procedure calls."),
        f"{MANUAL}#inline-assembly": doc("Manual - Inline Assembly",
            f"{MANUAL}#inline-assembly",
            "Writing inline assembly for architecture-specific operations."),
        f"{MANUAL}#nogc-pragma": doc("Manual - NoGC Pragma",
            f"{MANUAL}#nogc-pragma",
            "Disabling the garbage collector for real-time or embedded systems."),
        f"{MANUAL}#simd-pragma": doc("Manual - SIMD Pragma",
            f"{MANUAL}#simd-pragma",
            "SIMD intrinsics for vectorized arithmetic operations."),
        f"{MANUAL}#compile-time-evaluation": doc("Manual - Compile-Time Eval",
            f"{MANUAL}#compile-time-evaluation",
            "Evaluating expressions at compile time for zero-cost abstractions."),
        f"{MANUAL}#procedural-type": doc("Manual - Procedural Type",
            f"{MANUAL}#procedural-type",
            "First-class procedure types for callbacks and function pointers."),
        MANUAL: doc("Manual (Full)",
            MANUAL,
            "Complete Nim language reference manual covering all features."),

        # Stdlib docs
        f"{DOCS}/system.html": doc("std/system",
            f"{DOCS}/system.html",
            "Nim's implicit prelude: built-in types, operators, and core procedures."),
        f"{DOCS}/os.html": doc("std/os",
            f"{DOCS}/os.html",
            "Operating system interface: file operations, env vars, process info, paths."),
        f"{DOCS}/osproc.html": doc("std/osproc",
            f"{DOCS}/osproc.html",
            "External process execution: spawn, communicate, capture output."),
        f"{DOCS}/strutils.html": doc("std/strutils",
            f"{DOCS}/strutils.html",
            "String manipulation: split, join, strip, formatting, case conversion."),
        f"{DOCS}/strformat.html": doc("std/strformat",
            f"{DOCS}/strformat.html",
            "Compile-time string interpolation with the fmt macro."),
        f"{DOCS}/options.html": doc("std/options",
            f"{DOCS}/options.html",
            "Optional values with some/none pattern for nullable results."),
        f"{DOCS}/math.html": doc("std/math",
            f"{DOCS}/math.html",
            "Mathematical functions: trig, logarithms, stats, and numeric utilities."),
        f"{DOCS}/times.html": doc("std/times",
            f"{DOCS}/times.html",
            "Date/time handling: DateTime, Duration, formatting, and arithmetic."),
        f"{DOCS}/json.html": doc("std/json",
            f"{DOCS}/json.html",
            "JSON parsing, construction, and serialization."),
        f"{DOCS}/marshal.html": doc("std/marshal",
            f"{DOCS}/marshal.html",
            "Built-in object serialization and deserialization."),
        f"{DOCS}/streams.html": doc("std/streams",
            f"{DOCS}/streams.html",
            "Abstract stream interface for file, string, and memory I/O."),
        f"{DOCS}/sets.html": doc("std/sets",
            f"{DOCS}/sets.html",
            "Hash set and ordered set collections for membership testing."),
        f"{DOCS}/tables.html": doc("std/tables",
            f"{DOCS}/tables.html",
            "Key-value mapping with hash tables, ordered tables, and count tables."),
        f"{DOCS}/deques.html": doc("std/deques",
            f"{DOCS}/deques.html",
            "Double-ended queue with O(1) add/remove at both ends."),
        f"{DOCS}/critbits.html": doc("std/critbits",
            f"{DOCS}/critbits.html",
            "Crit-bit trees: memory-efficient string-keyed maps."),
        f"{DOCS}/sharedtables.html": doc("std/sharedtables",
            f"{DOCS}/sharedtables.html",
            "Thread-safe hash tables for concurrent access."),
        f"{DOCS}/re.html": doc("std/re",
            f"{DOCS}/re.html",
            "Regular expressions with PCRE-based matching, capture groups, and substitution."),
        f"{DOCS}/asyncdispatch.html": doc("std/asyncdispatch",
            f"{DOCS}/asyncdispatch.html",
            "Async/await event loop: futures, callbacks, and concurrent I/O."),
        f"{DOCS}/asyncnet.html": doc("std/asyncnet",
            f"{DOCS}/asyncnet.html",
            "Async TCP/UDP networking with non-blocking sockets."),
        f"{DOCS}/asyncio.html": doc("std/asyncio",
            f"{DOCS}/asyncio.html",
            "Async wrappers for file system I/O and streams."),
        f"{DOCS}/threadpool.html": doc("std/threadpool",
            f"{DOCS}/threadpool.html",
            "Spawn-based parallelism with work-stealing thread pools."),
        f"{DOCS}/channels.html": doc("std/channels",
            f"{DOCS}/channels.html",
            "Thread-safe message passing with channels."),
        f"{DOCS}/locks.html": doc("std/locks",
            f"{DOCS}/locks.html",
            "Mutex locks and condition variables for thread synchronization."),
        f"{DOCS}/atomics.html": doc("std/atomics",
            f"{DOCS}/atomics.html",
            "Lock-free atomic operations on shared memory."),
        f"{DOCS}/macros.html": doc("std/macros",
            f"{DOCS}/macros.html",
            "Compile-time AST manipulation: building, inspecting, and transforming code."),
        f"{DOCS}/unittest.html": doc("std/unittest",
            f"{DOCS}/unittest.html",
            "Unit testing framework with assertions, suites, and test discovery."),
        f"{DOCS}/parseopt.html": doc("std/parseopt",
            f"{DOCS}/parseopt.html",
            "Command-line argument parsing for CLI applications."),
        f"{DOCS}/parsecsv.html": doc("std/parsecsv",
            f"{DOCS}/parsecsv.html",
            "CSV file parsing with support for custom delimiters and quoting."),
        f"{DOCS}/parsecfg.html": doc("std/parsecfg",
            f"{DOCS}/parsecfg.html",
            "Configuration file parser for INI-style settings."),
        f"{DOCS}/pegs.html": doc("std/pegs",
            f"{DOCS}/pegs.html",
            "Parsing Expression Grammars for structured text parsing."),
        f"{DOCS}/base64.html": doc("std/base64",
            f"{DOCS}/base64.html",
            "Base64 encoding and decoding for binary data transport."),
        f"{DOCS}/sha1.html": doc("std/sha1",
            f"{DOCS}/sha1.html",
            "SHA-1 hashing, HMAC support, and secure digest computation."),
        f"{DOCS}/nimc.html": doc("Nim Compiler User Guide",
            f"{DOCS}/nimc.html",
            "Compiler flags, optimization, cross-compilation, and build configuration."),
        f"{DOCS}/nimc.html#compiler-usage": doc("Nim Compiler - Usage",
            f"{DOCS}/nimc.html#compiler-usage",
            "Command-line invocation, flags, and build modes for the Nim compiler."),
        f"{DOCS}/nimc.html#compiler-usage-command-line-switches": doc("Compiler - Flags Reference",
            f"{DOCS}/nimc.html#compiler-usage-command-line-switches",
            "Complete list of compiler command-line switches and their effects."),
        f"{DOCS}/nimc.html#configuration-files": doc("Compiler - Config Files",
            f"{DOCS}/nimc.html#configuration-files",
            "Project and global .cfg configuration files for the Nim compiler."),
        f"{DOCS}/nimc.html#cross-compilation": doc("Compiler - Cross-Compilation",
            f"{DOCS}/nimc.html#cross-compilation",
            "Cross-compiling Nim to different CPU architectures and operating systems."),
        f"{DOCS}/nimc.html#compilation-to-javascript": doc("Compiler - JS Target",
            f"{DOCS}/nimc.html#compilation-to-javascript",
            "Compiling Nim to JavaScript for browser and Node.js targets."),
        f"{DOCS}/nimc.html#ccompiler": doc("Compiler - C/C++ Backend",
            f"{DOCS}/nimc.html#ccompiler",
            "Configuring the C and C++ compilation backends."),
        f"{DOCS}/nimc.html#profiling": doc("Compiler - Profiling",
            f"{DOCS}/nimc.html#profiling",
            "Profiling Nim programs to identify performance bottlenecks."),
        f"{DOCS}/nimble.html": doc("Nimble Guide",
            f"{DOCS}/nimble.html",
            "Nim's package manager: creating packages, dependencies, and publishing."),
        f"{DOCS}/jsffi.html": doc("JS FFI",
            f"{DOCS}/jsffi.html",
            "Interfacing with JavaScript from Nim compiled to JS."),
        f"{DOCS}/nims.html": doc("NimScript",
            f"{DOCS}/nims.html",
            "Nim as a scripting language with .nims build files."),
        f"{DOCS}/nimsuggest.html": doc("Nimsuggest",
            f"{DOCS}/nimsuggest.html",
            "LSP server and IDE integration for Nim: autocomplete, goto-def, hints."),
        f"{DOCS}/docgen.html": doc("Docgen",
            f"{DOCS}/docgen.html",
            "Generating documentation from Nim source code comments."),
        f"{DOCS}/hcr.html": doc("Hot Code Reloading",
            f"{DOCS}/hcr.html",
            "Replacing code at runtime without restarting the application."),
        f"{DOCS}/memfiles.html": doc("std/memfiles",
            f"{DOCS}/memfiles.html",
            "Memory-mapped file I/O for efficient large file access."),
        f"{DOCS}/net.html": doc("std/net",
            f"{DOCS}/net.html",
            "Socket programming: TCP, UDP, DNS resolution, and networking primitives."),
        f"{DOCS}/httpclient.html": doc("std/httpclient",
            f"{DOCS}/httpclient.html",
            "HTTP client for making requests to web servers."),
        f"{DOCS}/asynchttpserver.html": doc("std/asynchttpserver",
            f"{DOCS}/asynchttpserver.html",
            "Async HTTP server for building web applications."),
        f"{DOCS}/uri.html": doc("std/uri",
            f"{DOCS}/uri.html",
            "URI parsing and manipulation utilities."),
        f"{DOCS}/db_sqlite.html": doc("std/db_sqlite",
            f"{DOCS}/db_sqlite.html",
            "SQLite database interface for persistent storage."),
        f"{DOCS}/signals.html": doc("std/signals",
            f"{DOCS}/signals.html",
            "Unix signal handling and custom signal dispatching."),
        f"{DOCS}/random.html": doc("std/random",
            f"{DOCS}/random.html",
            "Random number generation, shuffling, and sampling utilities."),
        f"{DOCS}/algorithm.html": doc("std/algorithm",
            f"{DOCS}/algorithm.html",
            "Sorting, searching, and other algorithmic operations on containers."),
        f"{DOCS}/nimpretty.html": doc("Nimpretty",
            f"{DOCS}/nimpretty.html",
            "Code formatter for consistent Nim source code style."),
        f"{DOCS}/nimlsp.html": doc("Nim LSP",
            f"{DOCS}/nimlsp.html",
            "Nim's Language Server Protocol implementation for IDE support."),
        f"{DOCS}/tools.html": doc("Nim Tools",
            f"{DOCS}/tools.html",
            "Available Nim development tools and their documentation."),

        # External
        "https://github.com/nim-lang/nimble": doc("Nimble - Package Manager",
            "https://github.com/nim-lang/nimble",
            "Nim's package manager: creating, publishing, and installing Nim packages."),
        "https://github.com/nim-lang/stdutils": doc("std/utils - Result Type",
            "https://github.com/nim-lang/stdutils",
            "Result/Option utility types and functional error handling patterns."),
        "https://github.com/dom96/choosenim": doc("Choosenim",
            "https://github.com/dom96/choosenim",
            "Nim version manager for installing and switching between Nim releases."),
        "https://nim-lang.org/docs/nep1.html": doc("NEP-1 - Style Guide",
            "https://nim-lang.org/docs/nep1.html",
            "Nim Enhancement Proposal #1: official code style and naming conventions."),
        "https://github.com/nimgl/nimgl": doc("NimGL",
            "https://github.com/nimgl/nimgl",
            "OpenGL, GLFW, and WebGL bindings for Nim graphics programming."),
        "https://github.com/johnnovak/illwill": doc("Illwill",
            "https://github.com/johnnovak/illwill",
            "Cross-platform terminal UI library inspired by Turbo Vision."),
        "https://github.com/treeform/fidget": doc("Fidget",
            "https://github.com/treeform/fidget",
            "Immediate-mode GUI library for Nim with reactive layout."),
        "https://github.com/yglukhov/nim-sdl2": doc("SDL2 Bindings",
            "https://github.com/yglukhov/nim-sdl2",
            "SDL2 multimedia library bindings for games and interactive applications."),
        "https://github.com/nim-lang/yaml": doc("YAML",
            "https://github.com/nim-lang/yaml",
            "YAML document parsing library for Nim."),
    }

    # Apply to every lesson
    for level in data["levels"]:
        for chapter in level["chapters"]:
            for lesson in chapter["lessons"]:
                if "docs" not in lesson:
                    lesson["docs"] = []
                new_docs = []
                for entry in lesson["docs"]:
                    if isinstance(entry, str):
                        # Bare URL — look up or fallback
                        entry = m.get(entry, doc("Nim Documentation", entry, ""))
                    new_docs.append(entry)
                lesson["docs"] = new_docs

    # Verify all lessons have docs
    total = 0
    for level in data["levels"]:
        for chapter in level["chapters"]:
            for lesson in chapter["lessons"]:
                total += 1
    print(f"Updated {total} lessons with structured docs.")

    with open("src/lessons.json", "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print("Written to src/lessons.json")


if __name__ == "__main__":
    main()
